mode:
  develop: true

sever:
  port: 8080

db:
  mysql:
    host: localhost
    port: 3306
    user: root
    password: 123456
    database: reggie
    charset: utf8
    maxIdleConns : 10
    maxOpenConns : 10
minio:
  endpoint: localhost:9000
  accessKeyID: qelApCjSUtpm8JSepybm
  secretAccessKey: a9AKFDeuNM9izC0EYBJ5ky00KZoGRUDxIUGIe6AK
  useSSL: false
  bucketName: reggie

